<?php $row_offset = 0; ?>
<?php if($projects != null){ ?>
	<style type="text/css">
		table.projects-grid tbody tr:hover {
			cursor: pointer;
			background: #fcf5dd;
		}
	</style>

	<form action="<?php echo($this->getUrl('*/*/save/')) ?>" method="post">
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>">
		<div class="content-header">
		    <table cellspacing="0">
		        <tr>
		            <td><h3>Projects</h3></td>
		            <td class="form-buttons">
		                <button class="scalable add" onclick="window.location='<?php echo($this->getUrl('*/*/create')) ?>'; return false;">
		                	<span>Add New Project</span>
		                </button>
		            </td>
		         </tr>
		    </table>
		</div>
		<div class="grid">
		    <div class="hor-scroll">
				<table cellspacing="0" class="data projects-grid">
					<thead>
						<tr class="headings">
							<th style='width:100px;'>Id</th>
							<th style='width:auto;'>Name</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach($projects as $project){ ++$row_offset; ?>
							<?php $project_url = $this->getUrl('*/*/edit', array('id' => $project->id)); ?>
							<tr class="<?php echo($row_offset % 2 == 0 ? 'odd' : 'even') ?>" onclick="window.location='<?php echo($project_url) ?>';">
								<td class="a-left"><?php echo($this->htmlEscape($project->id)) ?></td>
								<td class="a-left"><?php echo($this->htmlEscape($project->name)) ?></td>
							</tr>
						<?php } ?>
					</tbody>
			    </table>
		    </div>
		</div>
	</form>
<?php } ?>