<?php
/**
 *
 *
 * @author Ashley Schroder (aschroder.com)
 * @copyright  Copyright (c) 2010 Ashley Schroder
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($log = $this->getLogData()): ?>
    <div class="page-head">
        <h3><?php echo $this->__('Event Details') ?></h3>
    </div>
    <div class="log-detail">
        <p><strong><?php echo $this->__('Send Log Id:') ?></strong> <?php echo $log->getSendId(); ?></p>
        <p><strong><?php echo $this->__('Type:') ?></strong> <?php echo $log->getType(); ?></p>
        <p><strong><?php echo $this->__('Created:') ?></strong> <?php echo $log->getCreatedAt(); ?></p>
	    <p><strong><?php echo $this->__('Message:') ?></strong></p>
	    <div>
	       <?php echo $log->getMessage(); ?>
	    </div>
    </div>
    <br/>
    <div class="button-set"><a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back to Event Log') ?></a></div><br />
<?php endif; ?>
