<?php $admin_helper = Mage::helper("adminhtml"); ?>

<form id="alphamail-login-form" action="<?php echo($this->getUrl('*/*/TryLogin/')) ?>" method="post">
	<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>">
	<div id="page:main-container">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend">Congratulations!</h4>
                <div class="form-buttons">
                </div>
            </div>
            <div class="fieldset fieldset-wide" id="base_fieldset">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr>
                                <td class="label">
                                    <p>Magento has successfully connected to AlphaMail.</p>
                                    <p>Start by heading to configuration and activate the module.</p>
                                </td>
                            </tr>
                            <tr>
                                <td class="label">
                                    <button type="button" class="scalable" onclick="window.location='<?php echo($admin_helper->getUrl("adminhtml/system_config/edit/section/alphamail")) ?>';">
                                        <span>Show Configuration</span>
                                    </button>

                                    <i>or</i>

                                    <button type="button" class="scalable" onclick="window.location='<?php echo($admin_helper->getUrl("alphamail/SingleSignOn")) ?>';">
                                        <span>Show AlphaMail Dashboard</span>
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
	</div>
</form>