<style type="text/css">
    table.projects-grid tbody tr:hover {
        cursor: pointer;
        background: #fcf5dd;
    }  
</style>
<script type="text/javascript">
    /*function deleteTemplate(){
        if(confirm(''))
    }*/
</script>

<script src="<?php echo $skin_path ?>/jquery.js" type="text/javascript" language="javascript"></script>
<script src="<?php echo $skin_path ?>/jquery-ui-1.8.15.custom.min.js" type="text/javascript" language="javascript"></script>
<script src="<?php echo $skin_path ?>/jquery.layout.js"></script> 
<script type="text/javascript" src="<?php echo $skin_path ?>/jquery.sparkline.min.js"></script>

<link rel="stylesheet" href="<?php echo $skin_path ?>/css/styles.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $skin_path ?>/css/fonts.css" type="text/css" />

<script src="<?php echo $skin_path ?>/messagebox.js"></script>

<script type="text/javascript" src="<?php echo $skin_path ?>/CodeMirror-2.18/lib/codemirror.js"></script>
<link rel="stylesheet" href="<?php echo $skin_path ?>/CodeMirror-2.18/lib/codemirror.css" type="text/css" />
<script type="text/javascript" src="<?php echo $skin_path ?>/CodeMirror-2.18/mode/xml/xml.js"></script>
<script type="text/javascript" src="<?php echo $skin_path ?>/CodeMirror-2.18/mode/javascript/javascript.js"></script>
<script type="text/javascript" src="<?php echo $skin_path ?>/CodeMirror-2.18/mode/css/css.js"></script>
<script type="text/javascript" src="<?php echo $skin_path ?>/CodeMirror-2.18/mode/clike/clike.js"></script>
<script type="text/javascript" src="<?php echo $skin_path ?>/CodeMirror-2.18/mode/comlang/comlang.js"></script>
<link rel="stylesheet" href="<?php echo $skin_path ?>/CodeMirror-2.18/theme/default.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $skin_path ?>/CodeMirror-2.18/theme/eclipse.css" type="text/css" />

<script>
    var source_cm;
    var selected_tid = 288;

    var scroll = {
        sourceTop: 0,
        sourceLeft: 0,
        designTop: 0,
        designLeft: 0
    };

    var mode = "design";
    var design_frame;

    function render_code_textarea(id) {
        /* styles a textatrea with the CodeMirror Editor */
        return CodeMirror.fromTextArea(document.getElementById(id), {
            mode: "clike",
            lineNumbers: true,
            matchBrackets: true,
            indentUnit: 8,
            indentWithTabs: true,
            enterMode: "keep",
            tabMode: "shift",
            onKeyEvent: function (editor, e) {
                
            }
        });
    };

    $(document).ready(function() {
        design_frame = document.getElementById("html_design_frame").contentWindow;
    
        /* style the html source with the CodeMirror Editor */
        source_cm = CodeMirror.fromTextArea(document.getElementById("html_version"), {
            mode: {name: "comlang", htmlMode: true},
            lineNumbers: true,
            matchBrackets: true,
            indentUnit: 8,
            indentWithTabs: true,
            enterMode: "keep",
            tabMode: "shift",
            onKeyEvent: function (editor, e) {
                //window.parent.set_unsaved(true);
            }
        });
        
        /* set the editor size */
        resize_editor();
        
        selected_tid = 287;

        $("#text_version").val(<?php echo(json_encode($template->content->text)) ?>);
        $("#html_version").val(<?php echo(json_encode($template->content->html)) ?>);
        source_cm.setValue(<?php echo(json_encode($template->content->html)) ?>);
        
        /* render design editor */
        renderEditor();
    });

    /* resize the editor to fit the window */
    function resize_editor() {
        var height = $(window).height() - 81;
    
        $("#html_design_frame").height(height);
        $(".CodeMirror-scroll").height(height);
        $("#html_preview_frame").height(height);
        $("#text_version").height(height);
        source_cm.refresh();
    }

    /* auto adjust the editor size */
    $(window).resize(function() { resize_editor(); });

    /* save a template */
    function save_template() {
        if (mode == "design") {
            syncEditor();
        }

        $("form#template_form").submit();
        
        return false;
    }
    
    /* switch between html and text version */
    function text_html(mode) {
        if (mode === "text") {
            $("#btn_txt").addClass("hdr_btn_active");
            $("#btn_txt").removeClass("hdr_btn");
            
            $("#btn_html").removeClass("hdr_btn_active");
            $("#btn_html").addClass("hdr_btn");
            
            $("#div_txt").show();
            $("#div_html").hide();
        } else {
            $("#btn_html").addClass("hdr_btn_active");
            $("#btn_html").removeClass("hdr_btn");
            
            $("#btn_txt").removeClass("hdr_btn_active");
            $("#btn_txt").addClass("hdr_btn");
        
            $("#div_txt").hide();
            $("#div_html").show();
        }
    }
    
    /* switch between design/preview/source mode */
    function source_preview(elem, m) {
        $(".small_tab_active").removeClass("small_tab_active");
        $(elem).addClass("small_tab_active");
        
        switch (m) {
            case "source":
                /* html source mode */
                $("#html_design").hide();
                $("#html_preview").hide();
                $("#html_source").show();
                
                if (this.mode == "design") {
                    /* sync editor content */
                    syncEditor();

                    /* set scroll position */
                    $(source_cm.getScrollerElement()).scrollTop(scroll.sourceTop);
                    $(source_cm.getScrollerElement()).scrollLeft(scroll.sourceLeft);
                }
            break;
            
            case "design":
                /* design mode */
                /* save scroll position */
                scroll.sourceTop = $(source_cm.getScrollerElement()).scrollTop();
                scroll.sourceLeft = $(source_cm.getScrollerElement()).scrollLeft();

                /* 'save' the content and render the editor */
                source_cm.save();
                renderEditor();
            
                $("#html_design").show();
                $("#html_preview").hide();
                $("#html_source").hide();
            break;

            case "preview":
                /* html preview mode */
                source_cm.save();
                $("#html_preview_frame").contents().find("html").html($("#html_version").val());
            
                $("#html_design").hide();
                $("#html_source").hide();
                $("#html_preview").show();
        }
        
        mode = m;
    }
    
    function renderEditor() {
        design_frame.setContent($("#html_version").val());
    }

    function syncEditor() {
        source_cm.setValue(design_frame.getContent());
        source_cm.refresh();
        source_cm.save();
    }
    
    /* stop an event from 'bubbling' */
    function stop_event(e) {
        if (!e) {
            e = window.event;
        }
        
        if (e.cancelBubble) {
            e.cancelBubble = true;
        } else {
            e.stopPropagation();
        }
    }
</script>

    </div>

<form id="template_form" action="<?php echo($this->getUrl('*/*/save/')) ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>">
    <div id="page:main-container">
        <div class="content-header">
            <table cellspacing="0">
                <tr>
                    <td><h3>Create New AlphaMail Template</h3></td>
                    <td class="form-buttons">
                        <button type="button" class="scalable back" onclick="window.location='<?php echo($this->getUrl('*/*/index')) ?>'">
                            <span>Back</span>
                        </button>
                        <button type="button" class="scalable save" onclick="submit();">
                            <span>Create Template</span>
                        </button>
                    </td>
                 </tr>
            </table>
        </div>
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend">Template Information</h4>
                <div class="form-buttons"></div>
            </div>
            <div class="fieldset fieldset-wide" id="base_fieldset">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr id="field_name">
                                <td class="label">
                                    <label for="name">Name&nbsp;<span class="required">*</span></label>
                                </td>
                                <td class="value">
                                    <input id="name" name="name" value="<?php echo($this->htmlEscape($template->name)) ?>" title="Template Name" type="text" class="input-text required-entry">
                                </td>
                            </tr>
                        </tbody>
                    </table>

<div class="c c_x2">
    <div class="widget">
        <div class="w_header wcolor_gray">
            <div id="btn_html" class="w_header_text hdr_btn_active" onclick="text_html('html');">HTML-version</div>
            <div id="btn_txt" class="w_header_text hdr_btn" onclick="text_html('text');">Text-version</div>
            <div class="w_header_text" style="float: right;">
                <div style="display: none;">
                <div style="float: left; margin-right: 12px; margin-left: 10px;">Charset:</div>
                <div style="float: left; margin-top: 4px; margin-right: 20px;">
                    <select class="txt" id="templ_charset">
                        <option value="utf-8" >UTF-8 (Unicode)</option>
                        <option value="iso-8859-1" >ISO-8859-1 (Latin1)</option>
                    </select>
                </div>
                </div>
            </div>
        </div>
        <div class="w_menu"></div>
        <div class="w_main">
            <div class="w_main_inner">
                <div id="div_html" class="w_main_inner2" style="margin-bottom: 12px; padding-top: 0; padding-left: 0; padding-right: 0;">
                    <div style="min-height: 210px;">
                        <div id="html_design">
                            <iframe id="html_design_frame" name="html_frame" src="<?php echo $skin_path ?>/editor.htm"></iframe>
                        </div>
                        <div id="html_source">
                            <textarea style="width: 100%; height: 210px;" id="html_version" name="html_version" class="txt" onclick="$(this).focus();"></textarea>
                        </div>
                        <div id="html_preview">
                            <iframe id="html_preview_frame"></iframe>
                        </div>
                    </div>
                    <div class="small_tab small_tab_active" style="margin-left: 4px;" onclick="source_preview(this, 'design');">Design</div>
                    <div class="small_tab" onclick="source_preview(this, 'source');">Källa</div>
                </div>
                
                <div id="div_txt" class="w_main_inner2" style="margin-bottom: 12px; padding-top: 0; padding-left: 0; padding-right: 0; display: none;">
                    <textarea style="width: 100%; height: 210px; padding: 0;" id="text_version" name="text_version" class="txt" onclick="$(this).focus();"></textarea>
                </div>
            </div>
        </div>
    </div>
</div>
                </div>
            </div>
        </div>
    </div>
</form>