<?php if(isset($url)){ ?>
	<style type="text/css">
		div#anchor-content {
			padding: 0px;
		}

		iframe#alphamail-sign-on-frame {
			width: 100%;
			border:0px;
			padding:0px;
			margin:0px;
			min-height: 600px;
		}
	</style>
	<iframe id="alphamail-sign-on-frame" src="<?php echo($url) ?>"></iframe>
<?php }else{ ?>
	<p>Unable to login. Please go to your AlphaMail configuration and enter a valid token.</p>
<?php } ?>